
<html lang="en">
<?php
include 'inc/header.phtml';
?>

<body>

<!-- Top Banner
================================================= -->
<section id="banner">
    <div class="container">

        <!-- Change Password Form
        ================================================= -->
        <div class="sign-up-form">
            <a  class="logo"><img src="images/logo.png" alt="Friend Finder"/></a>
            <h2 class="text-white">Change Password</h2>
            <div class="line-divider"></div>
            <div class="form-wrapper">
                <p class="signup-text">User: <?php  echo $_SESSION["UserName"]; ?></p>
                <form action="" method="post">
                    <fieldset class="form-group">
                        <input type="password" class="form-control" id="old-password" placeholder="Enter an old password" name="old_password">
                    </fieldset>
                    <fieldset class="form-group">
                        <input type="password" class="form-control" id="new-password" placeholder="Enter a new password" name="new_password">
                    </fieldset>
                    <fieldset class="form-group">
                        <input type="password" class="form-control" id="confirm-password" placeholder="Confirm new password" name="confirm_password">
                    </fieldset>
                    <button class="btn-secondary" id="change-password" name="change_password" >Change Password</button>
                </form>

            </div>
            <a href="index.php?action=login">No change, login now?</a>
            <img class="form-shadow" src="images/bottom-shadow.png" alt="" />
        </div>
    </div>
</section>

--><?php
?>

<script>
    $("#change-password").click(function(){
        console.log("test javascript");
    });
    
</script>

</body>
</html>
