<!DOCTYPE html>
<html lang="en">
<title>Home | Check what new information today</title>

<?php

require_once ('inc/header.phtml');
?>

<body>

<!-- Header
================================================= -->

<!--Header End-->

<div id="page-contents">
    <div class="container">
        <div class="row">

            <!-- Newsfeed Common Side Bar Left
            ================================================= -->
            <div class="col-md-3 static">
                <div class="profile-card">
                    <img src="<?php  echo $_SESSION["Avatar"]; ?>" alt="user" class="profile-photo" />
                    <h5><a href="timeline.html" class="text-white"><?php  echo $_SESSION["UserName"]; ?></a></h5>
                    <a href="#" class="text-white"><i class="ion ion-android-person-add"></i> 0 Answer </a>
                </div><!--profile card ends-->
                <ul class="nav-news-feed">
                    <h4 class="grey">Categories</h4>
                    <li><i class="icon ion-ios-paper"></i><div><a href="index.php?catName=Books">Books</a></div></li>
                    <li><i class="icon ion-ios-people"></i><div><a href="index.php?catName=Technology">Technology</a></div></li>
                    <li><i class="icon ion-ios-people-outline"></i><div><a href="index.php?catName=Science">Science</a></div></li>
                    <li><i class="icon ion-chatboxes"></i><div><a href="index.php?catName=Language">Language</a></div></li>
                    <li><i class="icon ion-images"></i><div><a href="index.php?catName=Health">Health</a></div></li>
                    <li><i class="icon ion-ios-videocam"></i><div><a href="index.php?catName=Movies">Movies</a></div></li>
                    <h4 class="grey">Tags</h4>
                    <div class="item1">
                        <select  name="tags" onchange="location = this.value;" >
                            <option selected value="" disabled selected name="tags"></option>
                            <option value="index.php?tagName=TV-SHOWS" >TV-SHOWS</option>
                            <option value="index.php?tagName=HBO">HBO</option>
                            <option value="index.php?tagName=NETFLIX">NETFLIX</option>
                            <option value="index.php?tagName=SPANISH">SPANISH</option>
                            <option value="index.php?tagName=PHP">PHP</option>
                            <option value="index.php?tagName=AJAX">AJAX</option>
                            <option value="index.php?tagName=MVC">MVC</option>
                            <option value="index.php?tagName=FRAMEWORK">FRAMEWORK</option>
                            <option value="index.php?tagName=BOOKS">BOOKS</option>
                            <option value="index.php?tagName=BIOLOGY">BIOLOGY</option>
                            <option value="index.php?tagName=ENGLISH">ENGLISH</option>
                            <option value="index.php?tagName=ASP.NET">ASP.NET</option>
                            <option value="index.php?tagName=EATING">EATING</option>
                            <option value="index.php?tagName=WORK-OUT">WORK-OUT</option>
                        </select>
                    </div>
                </ul>
            </div>
            <div class="col-md-7">


            <!-- Post Create Box
                ================================================= -->
               <!-- <div class="create-post">
                    <div class="row">
                        <div class="col-md-7 col-sm-7">
                            <div class="form-group">
                                <img src="images/users/user-1.jpg" alt="" class="profile-photo-md" />
                                <textarea name="texts" id="exampleTextarea" cols="30" rows="1" class="form-control" placeholder="Write what you wish"></textarea>
                            </div>
                        </div>
                        <div class="col-md-5 col-sm-5">
                            <div class="tools">
                                <ul class="publishing-tools list-inline">
                                    <li><a href="#"><i class="ion-compose"></i></a></li>
                                    <li><a href="#"><i class="ion-images"></i></a></li>
                                    <li><a href="#"><i class="ion-ios-videocam"></i></a></li>
                                    <li><a href="#"><i class="ion-map"></i></a></li>
                                </ul>
                                <button class="btn btn-primary pull-right">Publish</button>
                            </div>
                        </div>
                    </div>
                </div>--><!-- Post Create Box End-->

                <!-- Post Content
                ================================================= -->
                <div class="post-content">
                    <h3><a class="profile-link">  <?php
                            foreach ($data as $value) {
                            echo $value->header;

                            ?>  </a> </h3>
                    <div class="post-container">
                        <img src="<?php  echo $value->Infor_User[0]->Avatar;  ?>" alt="user" class="profile-photo-md pull-left" />
                        <div class="post-detail">
                            <div class="user-info">
                                <h5><a href="" class="profile-link"><?php  echo $value->Infor_User[0]->Name;  ?></a> <span class="following"><?php  echo $value->categories;  ?></span></h5>
                                <p class="text-muted"><?php  echo $value->date_created;  ?></p>
                            </div>
                            <div class="reaction">
                                <a class="heart"><i class="fa fa-heart"></i> <?php  echo $value->like;  
                                echo '
                                <script src="./js/like.js">                                 
                                </script>
                                ';?> </a>
                                <a class="btn text"><i class="fa fa-ellipsis-v"></i> </a>
                            </div>
                            <div class="line-divider"></div>
                            <div class="post-text">
                                <p><?php  echo $value->detail;
                                    ?> </i></p>
                            </div>
                            <div class="line-divider"></div>
                            <?php
                            for ($x = 0; $x < count($value->Answer); $x++) { ?>
                            <div class="post-comment">
                                <img src="<?php  echo $value->Infor_User_Comment[$x]->Avatar;  ?>" alt="" class="profile-photo-sm" />
                                <p><a href="timeline.html" class="profile-link"><?php  echo $value->Infor_User_Comment[$x]->Name;  ?> </a><?php  echo $value->Answer[$x]->date;  ?><br><?php  echo $value->Answer[$x]->Answer;  ?> </p>
                            </div>
                                <a class="heart"><i class="fa fa-heart"></i> <?php  echo $value->Answer[$x]->like;  
                                echo '
                                <script src="./js/like.js">                                 
                                </script>
                                ';?> </a>
                                <a class="btn text"><i class="fa fa-ellipsis-v"></i> </a>
                                <div class="line-divider"></div>
                                <?php
                            }
                            ?>
                            <div class="post-comment">
                                <img src="<?php  echo $_SESSION["Avatar"]; ?>" alt="" class="profile-photo-sm" />
                                <form action="" class="form-container" method="POST">
                                    <div class="item">
                                        <textarea id="instructions" rows="5" cols="270" placeholder="Write detail question" name="comment"></textarea>
                                    </div>
                                    <br>
                                        <button class="btn btn-primary  " type="submit" name = "add_comment"  >Submit</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>

                <?php
                }
                ?>
            </div>

            <!-- Newsfeed Common Side Bar Right
            ================================================= -->
            <div class="col-md-2 static">
                <div class="suggestions" id="sticky-sidebar">
                    <h4 class="grey">Member Of Month</h4>
                    <div class="follow-user">
                        <img src="images/users/user-11.jpg" alt="" class="profile-photo-sm pull-left" />
                        <div>
                            <h5><a href="timeline.html">Cris Haris</a></h5>
                            <a  class="text-green">0 Answers </a>
                        </div>
                    </div>
                    <div class="follow-user">
                        <img src="images/users/user-12.jpg" alt="" class="profile-photo-sm pull-left" />
                        <div>
                            <h5><a href="timeline.html">Cris Haris</a></h5>
                            <a href="#" class="text-green">Add friend</a>
                        </div>
                    </div>
                    <div class="follow-user">
                        <img src="images/users/user-13.jpg" alt="" class="profile-photo-sm pull-left" />
                        <div>
                            <h5><a href="timeline.html">Brian Walton</a></h5>
                            <a href="#" class="text-green">Add friend</a>
                        </div>
                    </div>
                    <div class="follow-user">
                        <img src="images/users/user-14.jpg" alt="" class="profile-photo-sm pull-left" />
                        <div>
                            <h5><a href="timeline.html">Olivia Steward</a></h5>
                            <a href="#" class="text-green">Add friend</a>
                        </div>
                    </div>
                    <div class="follow-user">
                        <img src="images/users/user-15.jpg" alt="" class="profile-photo-sm pull-left" />
                        <div>
                            <h5><a href="timeline.html">Sophia Page</a></h5>
                            <a href="#" class="text-green">Add friend</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Footer
================================================= -->
<?php

require_once 'inc/footer.phtml';


?>


</body>
</html>
