
<html lang="en">
<?php

require_once ('inc/header.phtml');
?>

  <body>

  <section class="page_404">
      <div class="container">
          <div class="row">
              <div class="col-sm-12 ">
                  <div class="col-sm-10 col-sm-offset-1  text-center">
                      <div class="four_zero_four_bg">
                          <h1 class="text-center ">
                              Cannot access this page</h1>


                      </div>

                      <div class="contant_box_404">
                          <h3 class="">
                              Requires login !!!!!
                          </h3>


                          <a href="index.php?action=login" class="btn btn-primary ">Go To Login</a>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </section>

    <?php

    require_once 'inc/footer.phtml';


    ?>
  </body>
</html>
