<!DOCTYPE html>
<html lang="en">
<title>Home | Check what new information today</title>

<?php

require_once ('inc/header.phtml');

?>


<!-- Header
================================================= -->

<!--Header End-->

<div id="page-contents">
    <div class="container">
        <div class="row">

            <!-- Newsfeed Common Side Bar Left.
            ================================================= -->
            <div class="col-md-3 static">
                <div class="profile-card">
                    <img src="<?php  echo $_SESSION["Avatar"]; ?>" alt="user" class="profile-photo" />
                    <h5><a href="timeline.phtml" class="text-white"><?php  echo $_SESSION["UserName"]; ?></a></h5>
                    <a href="#" class="text-white"><i class="ion ion-android-person-add"></i> 0 Answer </a>
                </div><!--profile card ends-->
                <ul class="nav-news-feed">
                    <h4 class="grey">Categories</h4>
                    <li><i class="icon ion-ios-paper"></i><div><a href="index.php?catName=Books">Books</a></div></li>
                    <li><i class="icon ion-ios-people"></i><div><a href="index.php?catName=Technology">Technology</a></div></li>
                    <li><i class="icon ion-ios-people-outline"></i><div><a href="index.php?catName=Science">Science</a></div></li>
                    <li><i class="icon ion-chatboxes"></i><div><a href="index.php?catName=Language">Language</a></div></li>
                    <li><i class="icon ion-images"></i><div><a href="index.php?catName=Health">Health</a></div></li>
                    <li><i class="icon ion-ios-videocam"></i><div><a href="index.php?catName=Movies">Movies</a></div></li>
                    <h4 class="grey">Tags</h4>
                    <div class="item1">
                        <select  name="tags" onchange="location = this.value;" >
                            <option selected value="" disabled selected name="tags"></option>
                            <option value="index.php?tagName=TV-SHOWS" >TV-SHOWS</option>
                            <option value="index.php?tagName=HBO">HBO</option>
                            <option value="index.php?tagName=NETFLIX">NETFLIX</option>
                            <option value="index.php?tagName=SPANISH">SPANISH</option>
                            <option value="index.php?tagName=PHP">PHP</option>
                            <option value="index.php?tagName=AJAX">AJAX</option>
                            <option value="index.php?tagName=MVC">MVC</option>
                            <option value="index.php?tagName=FRAMEWORK">FRAMEWORK</option>
                            <option value="index.php?tagName=BOOKS">BOOKS</option>
                            <option value="index.php?tagName=BIOLOGY">BIOLOGY</option>
                            <option value="index.php?tagName=ENGLISH">ENGLISH</option>
                            <option value="index.php?tagName=ASP.NET">ASP.NET</option>
                            <option value="index.php?tagName=EATING">EATING</option>
                            <option value="index.php?tagName=WORK-OUT">WORK-OUT</option>
                        </select>
                    </div>
                </ul>
            </div>
            <div class="col-md-7">

                <!-- Post Create Box
                ================================================= -->
                <div class="report">
                    <div class="">
                        <div class="">
                            <a class=" btn btn-primary "  href="index.php" >+ Back to Index </a>

                            <div class="form-popup" id="myForm">
                                <form action="" class="form-container" method="POST" enctype="multipart/form-data">
                                    <h3> <label for="name">Reason for reporting</label></h3>
                                    <!--<input  id="name" type="text" name="name" width="280" required/>-->
                                    <textarea id="name" rows="5" cols="270" placeholder="Write your reason" name="Detail"></textarea>
                                    <div class="flax">
                                        <button class="btn btn-primary  " type="submit"name = "report_post" href="index.php" >Submit</button>

                                    </div>
                                </form>

                            </div>




                        </div>


                    </div>
                </div><!-- Post Report Box End-->


            </div>

            <!-- Newsfeed Common Side Bar Right
            ================================================= -->
            <div class="col-md-2 static">
                <div class="suggestions" id="sticky-sidebar">
                    <h4 class="grey">Member Of Month</h4>
                    <div class="follow-user">
                        <img src="images/users/user-11.jpg" alt="" class="profile-photo-sm pull-left" />
                        <div>
                            <h5><a href="timeline.html">Cris Haris</a></h5>
                            <a  class="text-green">0 Answers </a>
                        </div>
                    </div>
                    <div class="follow-user">
                        <img src="images/users/user-12.jpg" alt="" class="profile-photo-sm pull-left" />
                        <div>
                            <h5><a href="timeline.html">Cris Haris</a></h5>
                            <a href="#" class="text-green">Add friend</a>
                        </div>
                    </div>
                    <div class="follow-user">
                        <img src="images/users/user-13.jpg" alt="" class="profile-photo-sm pull-left" />
                        <div>
                            <h5><a href="timeline.html">Brian Walton</a></h5>
                            <a href="#" class="text-green">Add friend</a>
                        </div>
                    </div>
                    <div class="follow-user">
                        <img src="images/users/user-14.jpg" alt="" class="profile-photo-sm pull-left" />
                        <div>
                            <h5><a href="timeline.html">Olivia Steward</a></h5>
                            <a href="#" class="text-green">Add friend</a>
                        </div>
                    </div>
                    <div class="follow-user">
                        <img src="images/users/user-15.jpg" alt="" class="profile-photo-sm pull-left" />
                        <div>
                            <h5><a href="timeline.html">Sophia Page</a></h5>
                            <a href="#" class="text-green">Add friend</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Footer
================================================= -->
<?php

require_once 'inc/footer.phtml';


?>


</body>
</html>
