
<html lang="en">
<?php
include 'inc/header.phtml';
?>

<body>

<!-- Top Banner
================================================= -->
<section id="banner">
    <div class="container">

        <!-- Sign Up Form
        ================================================= -->
        <div class="sign-up-form">
            <a  class="logo"><img src="images/logo.png" alt="Friend Finder"/></a>
            <h2 class="text-white">Let’s begin the adventure</h2>
            <div class="line-divider"></div>
            <div class="form-wrapper">
                <p class="signup-text">Sign up now and find awesome knowledge around the world</p>
                <form action="" method="post">
                    <fieldset class="form-group">
                        <input type="text" class="form-control" id="example-name" placeholder="Enter email" name="email">
                    </fieldset>
                    <fieldset class="form-group">
                        <input type="password" class="form-control" id="example-password" placeholder="Enter a password" name="password">
                    </fieldset>
                    <fieldset class="form-group">
                        <input type="text" class="form-control" id="example-name" placeholder="Enter address" name="address">
                    </fieldset>
                    <fieldset class="form-group">
                        <input type="text" class="form-control" id="example-name" placeholder="Enter name" name="name">
                    </fieldset>
                    <fieldset class="form-group">
                        <input type="number" class="form-control" id="example-name" placeholder="Enter phone" name="phone">
                    </fieldset>
                    <fieldset class="form-group">
                        <input type="date" class="form-control" id="example-name" placeholder="Enter birthday" name="birthday">
                    </fieldset>
                    <fieldset class="form-group">
                        <input type="file" class="form-control" id="example-name" placeholder="Select avatar" name="avatar">
                    </fieldset>
                    <p>By signning up you agree to the terms</p>

                    <button class="btn-secondary" name="sign_up" >Sign up</button>
                </form>

            </div>
            <a href="index.php?action=login">Already have an account? Sign in</a>
            <img class="form-shadow" src="images/bottom-shadow.png" alt="" />
        </div><!-- Sign Up Form End -->

        <!--<svg class="arrows hidden-xs hidden-sm">
            <path class="a1" d="M0 0 L30 32 L60 0"></path>
            <path class="a2" d="M0 20 L30 52 L60 20"></path>
            <path class="a3" d="M0 40 L30 72 L60 40"></path>
        </svg>-->
    </div>
</section>

--><?php
/*
require_once 'inc/footer.phtml';


*/?>

</body>
</html>
