<!DOCTYPE html>
<html lang="en">
<?php
include 'inc/header.phtml';
?>

<body>
  <body>



    <div class="container">

      <!-- Timeline
      ================================================= -->
      <div class="timeline">
        <div class="timeline-cover">

          <!--Timeline Menu for Large Screens-->
          <div class="timeline-nav-bar hidden-sm hidden-xs">
            <div class="row">
              <div class="col-md-3">
                <div class="profile-info">
                    <img src="<?php  echo $_SESSION["Profile_Avatar"]; ?>" alt="user" class="profile-photo" />
                    <h5><a href="timeline-about.phtml"><?php  echo $_SESSION["Profile_UserName"]; ?></a></h5>
                    <p class="text-muted"><?php  echo $_SESSION["Profile_isAdmin"]; ?></p>
                </div>
              </div>
              <div class="col-md-9">
                <ul class="list-inline profile-menu">
                  <li><a href="timeline.html">Timeline</a></li>
                  <li><a href="timeline-about.html" class="active">About</a></li>
                  <li><a href="timeline-album.html">Album</a></li>
                  <li><a href="timeline-friends.html">Friends</a></li>
                </ul>
                <ul class="follow-me list-inline">
                  <li><button class="btn-primary">Add Friend</button></li>
                </ul>
              </div>
            </div>
          </div><!--Timeline Menu for Large Screens End-->

          <!--Timeline Menu for Small Screens-->
          <div class="navbar-mobile hidden-lg hidden-md">
            <div class="profile-info">
              <img src="<?php  echo $_SESSION["Profile_Avatar"]; ?>" alt="user" class="profile-photo" />
              <h5><a href="timeline-about.phtml"><?php  echo $_SESSION["Profile_UserName"]; ?></a></h5>
              <p class="text-muted"><?php  echo $_SESSION["Profile_isAdmin"]; ?></p>
            </div>
            <div class="mobile-menu">
              <ul class="list-inline">
                <li><a href="timline.html">Timeline</a></li>
                <li><a href="timeline-about.html" class="active">About</a></li>
                <li><a href="timeline-album.html">Album</a></li>
                <li><a href="timeline-friends.html">Friends</a></li>
              </ul>
              <button class="btn-primary">Add Friend</button>
            </div>
          </div><!--Timeline Menu for Small Screens End-->

        </div>
        <div id="page-contents">
          <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-7">

              <!-- About
              ================================================= -->
              <div class="about-profile">
                <div class="about-content-block">
                  <h4 class="grey"><i class="ion-ios-information-outline icon-in-title"></i> Personal Information</h4>
                    <h5>Name: <?php  echo $_SESSION["Profile_UserName"]; ?></h5>
                    <h5>Birthday: <?php  echo $_SESSION["Profile_Birthday"]; ?></h5>
                    <h5>Address: <?php  echo $_SESSION["Profile_Address"]; ?></h5>
                    <h5>Phone: <?php  echo $_SESSION["Profile_Phone"]; ?></h5>
                    <h5>Email: <?php  echo $_SESSION["Profile_Email"]; ?></h5>
                    <h5>Role: <?php  echo $_SESSION["Profile_isAdmin"]; ?></h5>
                    <h5>Number of Posts: <?php  echo $_SESSION["Profile_NumberofPosts"]; ?></h5>
                    <h5>Number of Answers: <?php  echo $_SESSION["Profile_NumberofAnswers"]; ?></h5>
                    <br>
                    <?php if($_SESSION["isAdmin"] == 1){echo '<a class=" btn btn-primary "  href="http://localhost:63342/Diendantrithuc/API/ExportDB.php" >Export All Data </a>';}?>
                </div>
                <div class="about-content-block">
                  <h4 class="grey"><i class="ion-ios-heart-outline icon-in-title"></i>Interests</h4>
                  <ul class="interests list-inline">
                    <li><span class="int-icons" title="Bycycle riding"><i class="icon ion-android-bicycle"></i></span></li>
                    <li><span class="int-icons" title="Photography"><i class="icon ion-ios-camera"></i></span></li>
                    <li><span class="int-icons" title="Shopping"><i class="icon ion-android-cart"></i></span></li>
                    <li><span class="int-icons" title="Traveling"><i class="icon ion-android-plane"></i></span></li>
                    <li><span class="int-icons" title="Eating"><i class="icon ion-android-restaurant"></i></span></li>
                  </ul>
                </div>
                <div class="about-content-block">
                  <h4 class="grey"><i class="ion-ios-chatbubble-outline icon-in-title"></i>Language</h4>
                    <ul>
                      <li><a href="">Russian</a></li>
                      <li><a href="">English</a></li>
                    </ul>
                </div>
              </div>
            </div>
            <div class="col-md-2 static">
              <div id="sticky-sidebar">
                <div class="feed-item">
                  <div class="live-activity">
                  <div class="about-content-block">
                  <ul class="interests list-inline">
                    <li><span class="int-icons" title="Bycycle riding"><i class="icon ion-social-facebook"></i></span></li>
                    <li><span class="int-icons" title="Photography"><i class="icon ion-social-twitter"></i></span></li>
                    <li><span class="int-icons" title="Shopping"><i class="icon ion-social-youtube"></i></span></li>
                  </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <?php

    require_once 'inc/footer.phtml';


    ?>
    
  </body>
</html>
